name: Test fenics_stubs

on:
  push:
    # The CI is executed on every push on every branch
    branches:
      - development
  pull_request:
    # The CI is executed on every pull request to the main branch
    branches:
      - development

  schedule:
    # The CI is executed every day at 8am
    - cron: "0 8 * * *"
jobs:
  check-code:
    runs-on: ubuntu-22.04
    # Runs against FEniCS main branch built the 16-01-2023
    container: ghcr.io/scientificcomputing/fenics-gmsh:2023-02-17a
    steps:
      # This action sets the current path to the root of your github repo
      - uses: actions/checkout@v3
      
      - name: "Install code"
        run: python3 -m pip install --no-binary=h5py .[dev] jupytext

      - name: Run example 1
        run: |
          cd examples/example1/
          jupytext example1.ipynb --to py
          python3 example1.py

      # - name: Run tests
      #   run: |
      #     cd tests/
      #     python3 -m pytest .